# Generated by Django 3.2.9 on 2021-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
                ('USE', models.CharField(choices=[('IMAGE RESTORATION', 'image restoration'), ('FACE MORPHING', 'face morphing'), ('IMAGE MIXING', 'image mixing')], max_length=255)),
                ('Fused_img', models.ImageField(blank=True, upload_to='images')),
                ('Expected_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('FUSION_METHOD', models.CharField(choices=[('meanmean', 'MEANMEAN'), ('meanmax', 'MEANMAX'), ('meanmin', 'MEANMIN'), ('maxmean', 'MAXMEAN'), ('maxmax', 'MAXMAX'), ('maxmin', 'MAXMIN'), ('minmean', 'MINMEAN'), ('minmax', 'MINMAX'), ('minmin', 'MINMIN')], max_length=50)),
            ],
        ),
    ]
