# Generated by Django 3.2.8 on 2021-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Fused_img',
            field=models.ImageField(blank=True, default='media\\images\\default.jfif', upload_to='images'),
        ),
    ]
