# Generated by Django 3.2.9 on 2021-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfuse', '0003_auto_20211124_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='fs8',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
