# Generated by Django 3.2.8 on 2021-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgfuse', '0005_alter_upload_fused_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='USE',
            field=models.CharField(choices=[('IMAGE RESTORATION', 'image restoration'), ('FACE MORPHING', 'face morphing'), ('IMAGE MIXING', 'image mixing')], default='IMAGE RESTORATION', max_length=255),
            preserve_default=False,
        ),
    ]
